spring:
  profiles:
    active: home
#    active: company
dubbo:
  application:
    name: yien_mall_kill
  registry:
    address: 127.0.0.1:2181
    protocol: zookeeper
  protocol:
    name: dubbo
    port: 20883
  monitor:
    protocol: registry
  scan:
    base-packages: com.zsl.kill
server:
  port: 8889
